/// Flutter icons Graviticons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/

import 'package:flutter/widgets.dart';

class Graviticons {
  Graviticons._();

  static const _kFontFam = 'Graviticons';
  static const String? _kFontPkg = null;

  static const IconData phoenix = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyrics = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyricsAwesome = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}