/// Flutter icons Phoenix_test
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class Phoenixtest {
  Phoenixtest._();

  static const _kFontFam = 'Phoenixtest';
  static const String _kFontPkg = null;

  static const IconData svging = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
